services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    ports:
      - 3000:3000/tcp

  grafana-dev:
    image: ghcr.io/volkovlabs/app:latest@sha256:7255f71881b7aa94198da4760a3c74fbbc5f6d16b592ec55f69c40c4e479b7be
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource,marcusolsson-static-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-calendar-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dev

  grafana-main:
    image: grafana/grafana:main@sha256:321abbc629cf32d8bd80834801ab5d6e021713171277a7dfbed6920dbbd9571a
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource,marcusolsson-static-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-calendar-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - main

  grafana-dep:
    image: grafana/grafana:11.0.0@sha256:0dc5a246ab16bb2c38a349fb588174e832b4c6c2db0981d0c3e6cd774ba66a54
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource,marcusolsson-static-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-calendar-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dependency

  playwright:
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - ./test:/app/test
      - ./playwright-report:/app/playwright-report
    depends_on:
      grafana:
        condition: service_healthy
    profiles:
      - e2e
      - playwright
